#!/usr/bin/env python3.8

import argparse
import pathlib
import subprocess
import os


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("repo_path", type=pathlib.Path)
    parser.add_argument("--crash", action="store_true")
    args = parser.parse_args()

    pseubench_path = pathlib.Path(__file__).resolve().parent
    repo_path = args.repo_path.resolve()

    process_args = ["python3", "-m", "pseubench", repo_path]
    if args.crash:
        process_args.append("--crash")

    repo_folder: pathlib.Path = pseubench_path / args.repo_path

    # Lean detection
    if (repo_folder / "leanpkg").exists() \
       or (repo_folder / "lean4-mode").exists() \
       or (repo_folder / "bin" / "leanpkg").exists():

        real_data_path = pseubench_path / "codespeed-pse" / "lean.json"
        process_args.extend(["--real-data", real_data_path])

    # Mini java in scala detection
    elif (repo_folder / "mjis" / "src" / "test" / "scala" / " mjis").exists():
        real_data_path = pseubench_path / "codespeed-pse" / "mjis.json"
        process_args.extend(["--real-data", real_data_path])

    # Danke, BS...
    os.chdir(pseubench_path)
    os.execvp("python3.8", process_args)
    # subprocess.run(process_args, cwd=pseubench_path)


if __name__ == '__main__':
    main()
